GO
USE [master]
GO
DROP DATABASE EHealthCare
GO
USE [master]
GO
CREATE DATABASE EHealthCare
GO
USE [EHealthCare]
GO
CREATE TABLE [dbo].[Country](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](64) NOT NULL,
	CONSTRAINT [PK_Country] PRIMARY KEY ([Id]),
	CONSTRAINT [UK_Country] UNIQUE ([Name]) );
GO
USE [EHealthCare]
GO
CREATE TABLE [dbo].[State](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](64) NOT NULL,
	[CountryId] [int] NOT NULL,
	CONSTRAINT [PK_State] PRIMARY KEY ([Id]),
	CONSTRAINT [UK_State] UNIQUE ([Name], [CountryId]),
	CONSTRAINT [FK_State_Country] FOREIGN KEY([CountryId]) REFERENCES [Country] ([Id]));
GO
USE [EHealthCare]
GO
CREATE TABLE [dbo].[City](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](64) NOT NULL,
	[StateId] [int] NOT NULL,
	CONSTRAINT [PK_City] PRIMARY KEY ([Id]),
	CONSTRAINT [UK_City] UNIQUE ([Name], [StateId]),
	CONSTRAINT [FK_City_State] FOREIGN KEY([StateId]) REFERENCES [State] ([Id]));
GO
USE [EHealthCare]
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](32) NULL,
	[Password] [varchar](512) NULL,
	[UserType] [tinyint] NOT NULL DEFAULT 4,
	[FirstName] [varchar](32) NOT NULL,
	[LastName] [varchar](32) NOT NULL,
	[Email] [varchar](128) NOT NULL,
	[MobileNo] [varchar](16) NULL,
	[Gender] [tinyint] NULL,
	[IsGoogle] [bit] NULL,
	[IsActive] [bit] NOT NULL,
	CONSTRAINT [PK_Users] PRIMARY KEY ([Id]),
	CONSTRAINT [UK_Users_Email] UNIQUE ([Email]),
	CONSTRAINT [UK_Users_Username] UNIQUE ([UserName]));
GO
USE [EHealthCare]
GO
CREATE TABLE [dbo].[UsersAddress](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[Building] [varchar](64) NOT NULL,
	[Street] [varchar](32) NULL,
	[CityId] [int] NOT NULL,
	CONSTRAINT [PK_UsersAddress] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_UsersAddress_User] FOREIGN KEY([UserId]) REFERENCES [Users] ([Id]),
	CONSTRAINT [FK_UsersAddress_City] FOREIGN KEY([CityId]) REFERENCES [City] ([Id]));
GO
USE [EHealthCare]
GO
CREATE TABLE [dbo].[Specialization](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](32) NOT NULL,
	[Time] [tinyint] NOT NULL,
	CONSTRAINT [PK_Specialization] PRIMARY KEY ([Id]),
	CONSTRAINT [UK_Specialization] UNIQUE ([Name]));
GO
USE [EHealthCare]
GO
CREATE TABLE [dbo].[DoctorSpecialization](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DoctorId] [int] NOT NULL,
	[SpecializationId] [int] NOT NULL,
	CONSTRAINT [PK_DoctorSpecialzation] PRIMARY KEY ([Id]),
	CONSTRAINT [UK_Doctor_Specialization] UNIQUE ([DoctorId], [SpecializationId]),
	CONSTRAINT [FK_DoctorSpecialization_Specialization] FOREIGN KEY([SpecializationId]) REFERENCES [Specialization] ([Id]),
	CONSTRAINT [FK_DoctorSpecialization_Users] FOREIGN KEY([DoctorId]) REFERENCES [Users] ([Id]));
GO
USE [EHealthCare]
GO
CREATE TABLE [dbo].[HospitalDoctor](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DoctorSpecializationId] [int] NOT NULL,
	[HospitalId] [int] NOT NULL,
	[Fees] [float] NOT NULL,
	[IsActive] [bit] NOT NULL,
	CONSTRAINT [PK_HospitalDoctor] PRIMARY KEY ([Id]),
	CONSTRAINT [UK_HospitalDoctor] UNIQUE ([DoctorSpecializationId], [HospitalId]),
	CONSTRAINT [FK_Doctor_Users] FOREIGN KEY([DoctorSpecializationId]) REFERENCES [DoctorSpecialization] ([Id]),
	CONSTRAINT [FK_Hospital_Users] FOREIGN KEY([HospitalId]) REFERENCES [Users] ([Id]));
GO
USE [EHealthCare]
GO
CREATE TABLE [dbo].[Appointment](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HospitalDoctorId] [int] NOT NULL,
	[PatientId] [int] NOT NULL,
	[AppointmentTime] [datetime] NOT NULL,
	[Status] [tinyint] NOT NULL,
	CONSTRAINT [PK_Appointment] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_HospitalDoctor_Appointment] FOREIGN KEY([HospitalDoctorId]) 	REFERENCES [HospitalDoctor]([Id]),
	CONSTRAINT [FK_Patient_Users] FOREIGN KEY([PatientId]) REFERENCES [Users] ([Id]));
GO
USE [EHealthCare]
GO
CREATE TABLE [dbo].[DoctorSchedule](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HospitalDoctorId] [int] NOT NULL,
	[ScheduleDate] [datetime] NOT NULL,
	[MorningStart] [time](7) NULL,
	[MorningEnd] [time](7) NULL,
	[EveningStart] [time](7) NULL,
	[EveningEnd] [time](7) NULL,
	[IsEmergency] [bit] NOT NULL,
	CONSTRAINT [PK_DoctorSchedule] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_HospitalDoctor] FOREIGN KEY([HospitalDoctorId]) REFERENCES [HospitalDoctor] ([Id]));
GO
USE [EHealthCare]
GO
CREATE TABLE [dbo].[UserImages](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[Name] [varchar](64) NOT NULL,
	CONSTRAINT [PK_UserImages] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_UserImages] UNIQUE ([Name]),
	CONSTRAINT [FK_UserImages_User] FOREIGN KEY([UserId]) REFERENCES [Users] ([Id]));

GO
INSERT [dbo].[Country] ([Name]) VALUES (N'India')
INSERT [dbo].[State] ([Name], [CountryId]) VALUES (N'Gujarat', 1)
INSERT [dbo].[State] ([Name], [CountryId]) VALUES (N'Madhya Pradesh', 1)
INSERT [dbo].[State] ([Name], [CountryId]) VALUES (N'Maharashtra', 1)
INSERT [dbo].[State] ([Name], [CountryId]) VALUES (N'Rajasthan', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Abrama', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Adalaj', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Adityana', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Advana', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ahmedabad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ahwa', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Alang', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ambaji', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ambaliyasan', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amod', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amreli', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amroli', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Anand', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Andada', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Anjar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Anklav', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ankleshwar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Anklesvar INA', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Antaliya', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Arambhada', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Asarma', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Atul', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Babra', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bag-e-Firdosh', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bagasara', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bahadarpar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bajipura', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bajva', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Balasinor', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Banaskantha', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bansda', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bantva', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bardoli', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Barwala', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bayad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bechar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bedi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Beyt', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhachau', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhanvad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bharuch', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bharuch INA', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhavnagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhayavadar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhestan', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhuj', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bilimora', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bilkha', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Billimora', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bodakdev', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bodeli', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bopal', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Boria', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Boriavi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Borsad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Botad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Cambay', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chaklasi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chala', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chalala', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chalthan', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chanasma', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chandisar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chandkheda', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chanod', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chaya', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chenpur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chhapi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chhaprabhatha', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chhatral', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chhota Udepur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chikhli', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chiloda', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chorvad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chotila', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dabhoi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dadara', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dahod', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dakor', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Damnagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Deesa', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Delvada', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Devgadh Baria', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Devsar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhandhuka', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhanera', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhangdhra', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhansura', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dharampur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhari', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhola', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dholka', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dholka Rural', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhoraji', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhrangadhra', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhrol', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhuva', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhuwaran', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Digvijaygram', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Disa', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dungar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dungarpur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dungra', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dwarka', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Flelanganj', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'GSFC Complex', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gadhda', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gandevi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gandhidham', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gandhinagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gariadhar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ghogha', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Godhra', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gondal', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hajira INA', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Halol', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Halvad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hansot', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Harij', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Himatnagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ichchhapor', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Idar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jafrabad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jalalpore', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jambusar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jamjodhpur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jamnagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jasdan', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jawaharnagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jetalsar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jetpur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jodiya', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Joshipura', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Junagadh', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kadi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kadodara', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kalavad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kali', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kaliawadi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kalol', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kalol INA', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kandla', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kanjari', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kanodar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kapadwanj', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karachiya', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karamsad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karjan', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kathial', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kathor', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Katpar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kavant', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Keshod', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kevadiya', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khambhaliya', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khambhat', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kharaghoda', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khed Brahma', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kheda', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kheralu', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kodinar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kosamba', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kundla', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kutch', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kutiyana', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lakhtar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lalpur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lambha', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lathi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Limbdi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Limla', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lunavada', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Madhapar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Maflipur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mahemdavad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mahudha', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mahuva', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mahuvar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Makarba', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Makarpura', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Makassar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Maktampur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Malia', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Malpur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manavadar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mandal', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mandvi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mangrol', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mansa', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Meghraj', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mehsana', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mendarla', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mithapur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Modasa', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mogravadi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Morbi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Morvi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mundra', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nadiad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Naliya', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nanakvada', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nandej', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nandesari', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nandesari INA', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Naroda', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Navagadh', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Navagam Ghed', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Navsari', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ode', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Okaf', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Okha', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Olpad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Paddhari', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Padra', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Palanpur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Palej', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pali', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Palitana', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Paliyad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pandesara', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Panoli', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pardi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Parnera', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Parvat', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Patan', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Patdi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Petlad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Petrochemical Complex', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Porbandar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Prantij', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Radhanpur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Raiya', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajkot', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajpipla', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajula', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ramod', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ranavav', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ranoli', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rapar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sahij', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Salaya', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sanand', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sankheda', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Santrampur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Saribujrang', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sarigam INA', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sayan', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sayla', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shahpur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shahwadi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shapar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shivrajpur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Siddhapur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sidhpur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sihor', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sika', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Singarva', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sinor', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sojitra', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sola', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Songadh', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Suraj Karadi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Surat', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Surendranagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Talaja', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Talala', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Talod', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tankara', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tarsali', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Thangadh', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tharad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Thasra', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Udyognagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ukai', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Umbergaon', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Umbergaon INA', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Umrala', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Umreth', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Un', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Una', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Unjha', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Upleta', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Utran', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Uttarsanda', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'V.U. Nagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'V.V. Nagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vadia', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vadla', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vadnagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vadodara', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vaghodia INA', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Valbhipur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vallabh Vidyanagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Valsad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Valsad INA', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vanthali', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vapi', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vapi INA', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vartej', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vasad', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vasna Borsad INA', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vaso', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Veraval', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vidyanagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vijalpor', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vijapur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vinchhiya', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vinzol', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Virpur', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Visavadar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Visnagar', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vyara', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Wadhwan', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Waghai', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Waghodia', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Wankaner', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Zalod', 1)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Agar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ajaigarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Akoda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Akodia', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Alampur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Alirajpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Alot', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amanganj', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amarkantak', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amarpatan', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amarwara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ambada', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ambah', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amla', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amlai', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Anjad', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Antri', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Anuppur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Aron', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ashoknagar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ashta', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Babai', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bada Malhera', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Badagaon', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Badagoan', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Badarwas', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Badawada', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Badi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Badkuhi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Badnagar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Badnawar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Badod', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Badoda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Badra', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bagh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bagli', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Baihar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Baikunthpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bakswaha', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Balaghat', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Baldeogarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bamaniya', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bamhani', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bamor', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bamora', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Banda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bangawan', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bansatar Kheda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Baraily', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Barela', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Barghat', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bargi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Barhi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Barigarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Barwaha', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Barwani', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Basoda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Begamganj', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Beohari', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Berasia', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Betma', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Betul', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Betul Bazar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhainsdehi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhamodi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhander', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhanpura', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bharveli', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhaurasa', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhavra', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhedaghat', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhikangaon', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhilakhedi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhind', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhitarwar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhopal', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhuibandh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Biaora', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bijawar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bijeypur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bijrauni', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bijuri', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bilaua', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bilpura', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bina Railway Colony', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bina-Etawa', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Birsinghpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Boda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Budhni', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Burhanpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Burhar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chachaura Binaganj', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chakghat', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chandameta Butar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chanderi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chandia', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chandla', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chaurai Khas', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chhatarpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chhindwara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chhota Chhindwara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chichli', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chitrakut', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Churhat', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Daboh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dabra', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Damoh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Damua', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Datia', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Deodara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Deori', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Deori Khas', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Depalpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Devendranagar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Devhara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dewas', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhamnod', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhana', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhanpuri', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dharampuri', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dighawani', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Diken', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dindori', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dola', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dumar Kachhar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dungariya Chhapara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gadarwara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gairatganj', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gandhi Sagar Hydel Colony', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ganjbasoda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Garhakota', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Garhi Malhara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Garoth', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gautapura', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ghansor', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ghuwara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gogaon', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gogapur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gohad', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gormi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Govindgarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Guna', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gurh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gwalior', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hanumana', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Harda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Harpalpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Harrai', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Harsud', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hatod', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hatpipalya', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hatta', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hindoria', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hirapur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hoshangabad', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ichhawar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Iklehra', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Indergarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Indore', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Isagarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Itarsi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jabalpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jabalpur Cantonment', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jabalpur G.C.F', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jaisinghnagar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jaithari', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jaitwara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jamai', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jaora', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jatachhapar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jatara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jawad', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jawar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jeronkhalsa', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jhabua', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jhundpura', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jiran', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jirapur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jobat', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Joura', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kailaras', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kaimur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kakarhati', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kalichhapar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kanad', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kannod', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kantaphod', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kareli', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karera', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kari', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karnawad', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karrapur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kasrawad', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Katangi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Katni', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kelhauri', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khachrod', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khajuraho', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khamaria', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khand', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khandwa', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khaniyadhana', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khargapur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khargone', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khategaon', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khetia', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khilchipur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khirkiya', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khujner', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khurai', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kolaras', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kotar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kothi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kotma', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kukshi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kumbhraj', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kurwai', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lahar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lakhnadon', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lateri', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Laundi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lidhora Khas', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lodhikheda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Loharda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Machalpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Madhogarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Maharajpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Maheshwar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mahidpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Maihar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Majholi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Makronia', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Maksi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Malaj Khand', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Malanpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Malhargarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manasa', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manawar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mandav', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mandideep', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mandla', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mandleshwar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mandsaur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manegaon', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mangawan', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manglaya Sadak', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mau', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mauganj', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Meghnagar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mehara Gaon', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mehgaon', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mhaugaon', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mhow', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mihona', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mohgaon', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Morar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Morena', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Morwa', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Multai', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mundi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mungaoli', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Murwara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nagda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nagod', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nagri', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Naigarhi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nainpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nalkheda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Namli', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Narayangarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Narsimhapur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Narsingarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Narsinghpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Narwar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nasrullaganj', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Naudhia', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Naugaon', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Naurozabad', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Neemuch', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nepa Nagar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Neuton Chikhli Kalan', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nimach', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Niwari', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Obedullaganj', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Omkareshwar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Orachha', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ordinance Factory Itarsi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pachmarhi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pachmarhi Cantonment', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pachore', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Palchorai', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Palda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Palera', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pali', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Panagar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Panara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pandaria', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pandhana', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pandhurna', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Panna', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pansemal', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Parasia', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pasan', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Patan', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Patharia', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pawai', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Petlawad', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Phuph Kalan', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pichhore', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pipariya', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pipliya Mandi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Piploda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pithampur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Polay Kalan', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Porsa', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Prithvipur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Raghogarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rahatgarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Raisen', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajakhedi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajgarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajnagar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rampur Baghelan', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rampur Naikin', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rampura', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ranapur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ranipura', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ratangarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ratlam', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ratlam Kasba', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rau', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rehli', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rehti', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rewa', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sabalgarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sagar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sagar Cantonment', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sailana', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sanawad', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sanchi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sanwer', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sarangpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sardarpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sarni', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Satai', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Satna', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Satwas', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sausar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sehore', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Semaria', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sendhwa', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Seondha', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Seoni', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Seoni Malwa', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sethia', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shahdol', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shahgarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shahpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shahpura', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shajapur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shamgarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sheopur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shivpuri', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shujalpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sidhi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sihora', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Singolo', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Singrauli', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sinhasa', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sirgora', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sirmaur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sironj', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sitamau', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sohagpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sonkatch', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Soyatkalan', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Suhagi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sultanpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Susner', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Suthaliya', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tal', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Talen', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tarana', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Taricharkalan', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tekanpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tendukheda', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Teonthar', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Thandia', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tikamgarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Timarni', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tirodi', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Udaipura', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ujjain', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ukwa', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Umaria', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Unchahara', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Unhel', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vehicle Factory Jabalpur', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vidisha', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vijayraghavgarh', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Waraseoni', 2)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Achalpur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Aheri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ahmadnagar Cantonment', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ahmadpur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ahmednagar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ajra', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Akalkot', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Akkalkuwa', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Akola', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Akot', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Alandi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Alibag', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Allapalli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Alore', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amalner', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ambad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ambajogai', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ambernath', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ambivali Tarf Wankhal', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amravati', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Anjangaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Arvi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ashta', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ashti', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Aurangabad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Aurangabad Cantonment', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ausa', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Babhulgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Badlapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Balapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ballarpur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Baramati', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Barshi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Basmat', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Beed', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhadravati', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhagur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhandara', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhigvan', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhingar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhiwandi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhokhardan', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhor', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhosari', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhum', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhusawal', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bid', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Biloli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Birwadi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Boisar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bop Khel', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Brahmapuri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Budhgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Buldana', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Buldhana', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Butibori', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chakan', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chalisgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chandrapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chandur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chandur Bazar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chandvad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chicholi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chikhala', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chikhaldara', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chikhli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chinchani', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chinchwad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chiplun', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chopda', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dabhol', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dahance', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dahanu', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Daharu', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dapoli Camp', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Darwa', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Daryapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dattapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Daund', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Davlameti', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Deglur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dehu Road', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Deolali', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Deolali Pravara', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Deoli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Desaiganj', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Deulgaon Raja', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dewhadi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dharangaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dharmabad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dharur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhatau', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhule', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Digdoh', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Diglur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Digras', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dombivli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dondaicha', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dudhani', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Durgapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dyane', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Edandol', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Eklahare', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Faizpur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Fekari', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gadchiroli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gadhinghaj', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gandhi Nagar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ganeshpur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gangakher', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gangapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gevrai', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ghatanji', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ghoti', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ghugus', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ghulewadi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Godoli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gondia', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Guhagar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hadgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Harnai Beach', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hinganghat', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hingoli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hupari', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ichalkaranji', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Igatpuri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Indapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jaisinghpur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jalgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jalna', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jamkhed', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jawhar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jaysingpur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jejuri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jintur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Junnar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kabnur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kagal', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kalamb', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kalamnuri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kalas', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kalmeshwar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kalundre', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kalyan', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kamthi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kamthi Cantonment', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kandari', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kandhar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kandri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kandri II', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kanhan', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kankavli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kannad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karanja', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karanje Tarf', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karivali', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karjat', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karmala', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kasara Budruk', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Katai', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Katkar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Katol', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kegaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khadkale', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khadki', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khamgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khapa', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kharadi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kharakvasla', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khed', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kherdi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khoni', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khopoli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khuldabad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kinwat', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kodoli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kolhapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kondumal', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kopargaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kopharad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Koradi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Koregaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Korochi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kudal', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kundaim', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kundalwadi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kurandvad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kurduvadi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kusgaon Budruk', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lanja', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lasalgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Latur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Loha', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lohegaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lonar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lonavala', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Madhavnagar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mahabaleshwar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mahad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mahadula', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Maindargi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Majalgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Malegaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Malgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Malkapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Malwan', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manadur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manchar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mangalvedhe', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mangrul Pir', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manmad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manor', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mansar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manwath', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mapuca', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Matheran', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mehkar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mhasla', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mhaswad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mira Bhayandar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Miraj', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mohpa', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mohpada', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Moram', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Morshi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mowad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mudkhed', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mukhed', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mul', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mulshi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mumbai', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Murbad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Murgud', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Murtijapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Murud', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nachane', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nagardeole', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nagothane', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nagpur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nakoda', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nalasopara', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Naldurg', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nanded', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nandgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nandura', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nandurbar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Narkhed', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nashik', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Navapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Navi Mumbai', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Navi Mumbai Panvel', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Neral', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nigdi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nilanga', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nildoh', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nimbhore', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ojhar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Osmanabad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pachgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pachora', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Padagha', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Paithan', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Palghar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pali', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Panchgani', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pandhakarwada', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pandharpur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Panhala', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Panvel', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Paranda', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Parbhani', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Parli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Parola', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Partur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pasthal', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Patan', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pathardi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pathri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Patur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pawni', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pen', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pethumri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Phaltan', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pimpri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Poladpur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pulgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pune', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pune Cantonment', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Purna', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Purushottamnagar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pusad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rahimatpur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rahta Pimplas', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rahuri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Raigad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajgurunagar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajura', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ramtek', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ratnagiri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ravalgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Raver', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Revadanda', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Risod', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Roha Ashtami', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sakri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sandor', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sangamner', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sangli', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sangole', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sasti', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sasvad', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Satana', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Satara', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Savantvadi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Savda', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Savner', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sawari Jawharnagar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Selu', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shahada', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shahapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shegaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shelar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shendurjana', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shirdi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shirgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shirpur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shirur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shirwal', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shivatkar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shrigonda', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shrirampur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shrirampur Rural', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sillewada', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sillod', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sindhudurg', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sindi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sindi Turf Hindnagar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sindkhed Raja', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Singnapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sinnar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sirur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sitasawangi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Solapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sonai', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sonegaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Soyagaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Srivardhan', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Surgana', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Talegaon Dabhade', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Taloda', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Taloja', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Talwade', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tarapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tasgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tathavade', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tekadi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Telhara', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Thane', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tirira', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Totaladoh', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Trimbak', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tuljapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tumsar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Uchgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Udgir', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ulhasnagar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Umarga', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Umarkhed', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Umarsara', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Umbar Pada Nandade', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Umred', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Umri Pragane Balapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Uran', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Uran Islampur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Utekhol', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vada', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vadgaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vadgaon Kasba', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vaijapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vanvadi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Varangaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vasai', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vasantnagar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vashind', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vengurla', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Virar', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Visapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vite', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vithalwadi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Wadi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Waghapur', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Wai', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Wajegaon', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Walani', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Wanadongri', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Wani', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Wardha', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Warora', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Warthi', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Warud', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Washim', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Yaval', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Yavatmal', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Yeola', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Yerkheda', 3)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Abu Road', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ajmer', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Aklera', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Alwar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Amet', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Antah', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Anupgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Asind', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bagar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bagru', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bahror', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bakani', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bali', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Balotra', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bandikui', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Banswara', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Baran', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bari', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bari Sadri', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Barmer', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Basi', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Basni Belima', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Baswa', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bayana', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Beawar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Begun', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhadasar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhadra', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhalariya', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bharatpur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhasawar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhawani Mandi', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhawri', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhilwara', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhindar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhinmal', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bhiwadi', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bijoliya Kalan', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bikaner', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bilara', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bissau', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Borkhera', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Budhpura', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Bundi', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chatsu', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chechat', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chhabra', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chhapar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chhipa Barod', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chhoti Sadri', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chirawa', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chittaurgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chittorgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Chomun', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Churu', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Daosa', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dariba', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dausa', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Deoli', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Deshnok', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Devgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Devli', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhariawad', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dhaulpur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dholpur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Didwana', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dig', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dungargarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Dungarpur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Falna', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Fatehnagar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Fatehpur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gajsinghpur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Galiakot', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ganganagar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gangapur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Goredi Chancha', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gothra', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Govindgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Gulabpura', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hanumangarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Hindaun', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Indragarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jahazpur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jaipur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jaisalmer', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jaiselmer', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jaitaran', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jalore', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jhalawar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jhalrapatan', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jhunjhunun', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jobner', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Jodhpur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kaithun', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kaman', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kankroli', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kanor', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kapasan', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kaprain', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karanpura', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Karauli', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kekri', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Keshorai Patan', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kesrisinghpur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khairthal', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khandela', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khanpur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kherli', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kherliganj', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kherwara Chhaoni', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Khetri', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kiranipura', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kishangarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kishangarh Ranwal', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kolvi Rajendrapura', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kot Putli', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kota', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kuchaman', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kuchera', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kumbhalgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kumbhkot', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kumher', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Kushalgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lachhmangarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ladnun', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lakheri', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Lalsot', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Losal', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Madanganj', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mahu Kalan', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mahwa', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Makrana', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Malpura', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mandal', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mandalgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mandawar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mandwa', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mangrol', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manohar Thana', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Manoharpur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Marwar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Merta', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Modak', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mount Abu', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mukandgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Mundwa', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nadbai', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Naenwa', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nagar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nagaur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Napasar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Naraina', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nasirabad', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nathdwara', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nawa', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nawalgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Neem Ka Thana', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Neemrana', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Newa Talai', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nimaj', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nimbahera', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Niwai', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nohar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Nokha', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'One SGM', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Padampur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pali', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Partapur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Parvatsar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pasoond', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Phalna', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Phalodi', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Phulera', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pilani', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pilibanga', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pindwara', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pipalia Kalan', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pipar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pirawa', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pokaran', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pratapgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Pushkar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Raipur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Raisinghnagar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajakhera', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajaldesar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rajsamand', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ramganj Mandi', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ramgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rani', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Raniwara', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ratan Nagar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ratangarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rawatbhata', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rawatsar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Rikhabdev', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Ringas', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sadri', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sadulshahar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sagwara', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Salumbar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sambhar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Samdari', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sanchor', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sangariya', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sangod', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sardarshahr', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sarwar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Satal Kheri', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sawai Madhopur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sewan Kalan', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Shahpura', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sheoganj', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sikar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sirohi', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Siwana', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sogariya', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sojat', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sojat Road', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sri Madhopur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sriganganagar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sujangarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Suket', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sumerpur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Sunel', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Surajgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Suratgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Swaroopganj', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Takhatgarh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Taranagar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Three STR', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tijara', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Toda Bhim', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Toda Raisingh', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Todra', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Tonk', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Udaipur', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Udpura', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Uniara', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vanasthali', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vidyavihar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Vijainagar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Viratnagar', 4)
INSERT [dbo].[City] ([Name], [StateId]) VALUES (N'Wer', 4)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Allergy', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Allergy & Immunology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Immunology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Immunopathology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Pediatric Allergy', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Anesthesiology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Critical Care Anesthesiology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Critical Care Medicine', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Pain Management', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Cardiovascular Disease', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Cardiovascular Surgery', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Interventional Cardiology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Pediatric Cardiology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Dermatology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Dermatopathology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Diabetes', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Pediatric Endocrinology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Reproductive Endocrinology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Emergency Medicine', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Urgent Care', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Family Practice', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Geriatric Family Practice', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'General Practice', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Geriatrics', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Rheumatology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Adolescent Medicine', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Diagnostic Laboratory Immunology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Gastroenterology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Hematology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Hepatology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Hospitalist', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Infectious Diseases', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Internal Medicine', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Nephrology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Nutrition', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Pulmonary Disease', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Pulmonary Critical Care Medicine', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Vascular Surgery', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Genetics', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Clinical Genetics', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Child Neurology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Clinical Neurophysiology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Neurological Surgery', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Neurology', 60)
INSERT [dbo].[Specialization] ([Name], [Time]) VALUES (N'Spinal Cord Injury', 60)
INSERT [dbo].[Users] ([UserName], [Password], [UserType], [FirstName], [LastName], [Email], [MobileNo], [Gender], [IsActive]) VALUES (N'Admin', N'I/C3xRDEhLw=', 1, N'Admin', N'EHealth Care', N'admin@gmail.com', N'123456', 1, 1)
INSERT [dbo].[Users] ([UserName], [Password], [UserType], [FirstName], [LastName], [Email], [MobileNo], [Gender], [IsActive]) VALUES (N'Abilities Expo', N'I/C3xRDEhLw=', 2, N'Abilities Expo', N' Houston', N'klara@shomex.com', N'123456', NULL, 1)
INSERT [dbo].[Users] ([UserName], [Password], [UserType], [FirstName], [LastName], [Email], [MobileNo], [Gender], [IsActive]) VALUES (N'ICEENN', N'I/C3xRDEhLw=', 2, N'ICEENN', N' Conference', N'kj.wilkinson@umontreal.ca', N'123456', NULL, 1)
INSERT [dbo].[Users] ([UserName], [Password], [UserType], [FirstName], [LastName], [Email], [MobileNo], [Gender], [IsActive]) VALUES (N'DavidWiebe', N'I/C3xRDEhLw=', 3, N'David', N'Wiebe', N'DavidWiebe@gmail.com', N'123456', 1, 1)
INSERT [dbo].[Users] ([UserName], [Password], [UserType], [FirstName], [LastName], [Email], [MobileNo], [Gender], [IsActive]) VALUES (N'RobertBisbee', N'I/C3xRDEhLw=', 3, N'Robert', N'Bisbee', N'RobertBisbee@gmail.com', N'123456', 1, 1)
INSERT [dbo].[Users] ([UserName], [Password], [UserType], [FirstName], [LastName], [Email], [MobileNo], [Gender], [IsActive]) VALUES (N'BinSung', N'I/C3xRDEhLw=', 3, N'Bin', N'Sung', N'BinSung@gmail.com', N'123456', 2, 1)
INSERT [dbo].[Users] ([UserName], [Password], [UserType], [FirstName], [LastName], [Email], [MobileNo], [Gender], [IsActive]) VALUES (N'AllisonHuebert', N'I/C3xRDEhLw=', 3, N'Allison', N'Huebert', N'allisonHuebert@gmail.com', N'123456', 2, 1)
INSERT [dbo].[UserImages] ([UserId], [Name]) VALUES (1, N'Profile-1.jpg')
INSERT [dbo].[UserImages] ([UserId], [Name]) VALUES (3, N'Profile-3.jpg')
GO
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(4, 1)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(5, 1)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(6, 1)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(7, 1)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(4, 2)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(5, 2)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(6, 2)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(7, 2)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(4, 3)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(5, 3)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(6, 3)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(7, 3)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(4, 4)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(5, 4)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(6, 4)
INSERT INTO DoctorSpecialization(DoctorId, SpecializationId) VALUES(7, 4)
INSERT INTO HospitalDoctor(DoctorSpecializationId, HospitalId, Fees, IsActive) VALUES(1, 2, 100, 1)
INSERT INTO HospitalDoctor(DoctorSpecializationId, HospitalId, Fees, IsActive) VALUES(1, 3, 100, 1)
INSERT INTO HospitalDoctor(DoctorSpecializationId, HospitalId, Fees, IsActive) VALUES(2, 2, 100, 1)
INSERT INTO HospitalDoctor(DoctorSpecializationId, HospitalId, Fees, IsActive) VALUES(2, 3, 100, 1)
INSERT INTO HospitalDoctor(DoctorSpecializationId, HospitalId, Fees, IsActive) VALUES(3, 2, 100, 1)
INSERT INTO HospitalDoctor(DoctorSpecializationId, HospitalId, Fees, IsActive) VALUES(4, 3, 100, 1)