//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCare.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSchedule
    {
        public int Id { get; set; }
        public int HospitalDoctorId { get; set; }

        public string HospitalName { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public Nullable<System.TimeSpan> MorningStart { get; set; }
        public Nullable<System.TimeSpan> MorningEnd { get; set; }
        public Nullable<System.TimeSpan> EveningStart { get; set; }
        public Nullable<System.TimeSpan> EveningEnd { get; set; }
        public bool IsEmergency { get; set; }
    
        public virtual HospitalDoctor HospitalDoctor { get; set; }
    }
}
