//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCare.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAddress
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Building { get; set; }
        public string Street { get; set; }
        public int CityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
    }
}
